// Static demo/fallback business ideas. Ported 1:1 from FALLBACK_IDEAS in
// the original sahara-x.html. Used for (a) grounding the RECO_SYSTEM
// prompt sent to Claude and (b) building a client-side fallback
// recommendation set if the Claude call fails. Mirrored server-side in
// backend/src/data/fallbackIdeas.js (see README "Assumptions").

export const FALLBACK_IDEAS = [
 {id:"fb-1",ideaName:"Mobile Vegetable & Grocery Cart",sector:"Retail",description:"A daily mobile cart bringing fresh vegetables and grocery essentials directly to households in your area, reducing the need for customers to travel to a market.",estimatedBudget:{min:10000,max:40000,display:"₹10K–₹40K"},feasibilityScore:8,whyThisFits:["Low starting capital","Minimal technical skill required","Daily cash-flow model"],demandSignal:"Estimated demand based on typical household grocery patterns in similar areas.",riskFactors:["Weather dependency","Perishable stock"],futureAdvice:"Start on a fixed local route, then add a second cart once demand is proven.",growthPotential:"Medium",governmentSchemeCategories:["retail","micro-enterprise"]},
 {id:"fb-2",ideaName:"Home-based Tiffin Service",sector:"Food",description:"A daily home-cooked meal subscription service for working individuals, students, or small offices nearby.",estimatedBudget:{min:15000,max:50000,display:"₹15K–₹50K"},feasibilityScore:9,whyThisFits:["Uses existing cooking skill","Can start from home kitchen","Recurring subscription revenue"],demandSignal:"Estimated demand from working professionals and students seeking home-style meals.",riskFactors:["Order volume fluctuation","Food safety compliance"],futureAdvice:"Formalise FSSAI registration early and consider a delivery partnership once orders grow.",growthPotential:"High",governmentSchemeCategories:["food","micro-enterprise"]},
 {id:"fb-3",ideaName:"Mobile Repair & Recharge Shop",sector:"Services",description:"A small shop or kiosk offering mobile phone repair, recharge, and accessory sales.",estimatedBudget:{min:20000,max:60000,display:"₹20K–₹60K"},feasibilityScore:9,whyThisFits:["Technical repair skill in demand","Low ongoing overhead","Multiple revenue streams"],demandSignal:"Estimated demand based on rising smartphone penetration in semi-urban markets.",riskFactors:["Fast-changing technology","Spare-part sourcing"],futureAdvice:"Add digital-payment and bill-pay services to diversify income.",growthPotential:"High",governmentSchemeCategories:["services","technology","micro-enterprise"]},
 {id:"fb-4",ideaName:"Solar Charging & Repair Kiosk",sector:"Energy",description:"A kiosk offering solar-based device charging and basic solar-equipment repair for the local community.",estimatedBudget:{min:30000,max:80000,display:"₹30K–₹80K"},feasibilityScore:7,whyThisFits:["Growing rural solar adoption","Recurring service income"],demandSignal:"Estimated demand in areas with unreliable grid electricity.",riskFactors:["Equipment maintenance","Upfront equipment cost"],futureAdvice:"Partner with a solar equipment distributor for warranty-backed servicing.",growthPotential:"Medium",governmentSchemeCategories:["energy","micro-enterprise"]},
 {id:"fb-5",ideaName:"Rural Digital Seva Kendra",sector:"Services",description:"A digital-services kiosk offering government-service applications, bill payments, and basic digital literacy assistance.",estimatedBudget:{min:30000,max:90000,display:"₹30K–₹90K"},feasibilityScore:9,whyThisFits:["Growing demand for digital access","Recognised support ecosystem"],demandSignal:"Estimated demand from residents needing local access to digital government services.",riskFactors:["Internet connectivity dependency"],futureAdvice:"Expand into printing, photography, and e-commerce pickup services over time.",growthPotential:"High",governmentSchemeCategories:["services","technology"]},
 {id:"fb-6",ideaName:"Mini Cold Storage",sector:"Agri-processing",description:"A small-scale cold storage facility helping local farmers store perishable produce and reduce post-harvest loss.",estimatedBudget:{min:200000,max:500000,display:"₹2L–₹5L"},feasibilityScore:7,whyThisFits:["Addresses a real local storage gap","Sector-specific infrastructure support available"],demandSignal:"Estimated demand based on typical post-harvest storage gaps in similar farming regions.",riskFactors:["High upfront capital","Electricity dependency"],futureAdvice:"Start with a smaller capacity unit and expand as farmer relationships grow.",growthPotential:"Medium",governmentSchemeCategories:["agriculture","logistics"]},
 {id:"fb-7",ideaName:"Rural Homestay",sector:"Tourism",description:"A registered homestay offering visitors an authentic stay experience with local meals and guided context.",estimatedBudget:{min:200000,max:600000,display:"₹2L–₹6L"},feasibilityScore:7,whyThisFits:["Uses existing home space","Local hospitality knowledge"],demandSignal:"Estimated demand tied to nearby tourist or pilgrimage footfall.",riskFactors:["Seasonality","Marketing reach"],futureAdvice:"List on regional homestay platforms and build a repeat-guest referral base.",growthPotential:"Medium",governmentSchemeCategories:["tourism"]},
];
